name: Build, Test, and Static Analysis

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Install Build Essentials
    - name: Install GCC and Make
      run: sudo apt-get update && sudo apt-get install -y build-essential

    # Step 3: Install Cppcheck
    - name: Install Cppcheck
      run: sudo apt-get install -y cppcheck

    # Step 4: Run Cppcheck
    - name: Run Cppcheck Static Analysis
      run: |
        cppcheck --enable=all --inconclusive --std=c++17 -Iinclude src/*.c
        if [ -s cppcheck-results.txt ]; then
          echo "Cppcheck found issues. See below:"
          cat cppcheck-results.txt
          exit 1
        fi
        
    # Step 5: Commit cppcheck-output.txt to the repository
    - name: Commit cppcheck-output.txt to the repository
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add cppcheck-output.txt
        git commit -m "Add cppcheck-output.txt with results"
        git push origin main
    
    # Step 6: Build the Project
    - name: Build the Project
      run: |
        make clean
        make VERBOSE=1

    # Step 7: Run the Main Program
    - name: Run Main Program
      run: ./bin/sensor_program > test_output.txt

    # Step 8: Run Unit Tests
    - name: Run Unit Tests
      run: ./bin/test_sensor

    # Step 9: Display Program Output
    - name: Display Program Output
      run: cat test_output.txt

    # Step 10: Check for Warnings
    - name: Check for Warnings
      run: |
        if grep -q "Warning:" test_output.txt; then
          echo "Warnings found in output!"
          exit 1
        fi
